// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: frictions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFrictions = `-- name: CountFrictions :one
SELECT count(*) FROM frictions
WHERE user_id = $1
  AND ($2::uuid IS NULL OR task_id = $2)
  AND ($3::uuid IS NULL OR work_slice_id = $3)
  AND ($4::text IS NULL OR pattern_tag = $4)
  AND (
    $5::bool IS NULL
    OR ($5::bool = true AND resolved_at IS NOT NULL)
    OR ($5::bool = false AND resolved_at IS NULL)
  )
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at < $7)
`

type CountFrictionsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	WorkSliceID pgtype.UUID        `json:"work_slice_id"`
	PatternTag  *string            `json:"pattern_tag"`
	Resolved    *bool              `json:"resolved"`
	FromTime    pgtype.Timestamptz `json:"from_time"`
	ToTime      pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) CountFrictions(ctx context.Context, arg CountFrictionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFrictions,
		arg.UserID,
		arg.TaskID,
		arg.WorkSliceID,
		arg.PatternTag,
		arg.Resolved,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFriction = `-- name: CreateFriction :one
INSERT INTO frictions (id, user_id, task_id, work_slice_id, pattern_tag, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, task_id, work_slice_id, description, resolved_at, resolution_note, metadata, created_at, updated_at, pattern_tag
`

type CreateFrictionParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	TaskID      pgtype.UUID `json:"task_id"`
	WorkSliceID pgtype.UUID `json:"work_slice_id"`
	PatternTag  string      `json:"pattern_tag"`
	Description string      `json:"description"`
}

func (q *Queries) CreateFriction(ctx context.Context, arg CreateFrictionParams) (Friction, error) {
	row := q.db.QueryRow(ctx, createFriction,
		arg.ID,
		arg.UserID,
		arg.TaskID,
		arg.WorkSliceID,
		arg.PatternTag,
		arg.Description,
	)
	var i Friction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.WorkSliceID,
		&i.Description,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PatternTag,
	)
	return i, err
}

const deleteFriction = `-- name: DeleteFriction :exec
DELETE FROM frictions WHERE id = $1 AND user_id = $2
`

type DeleteFrictionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteFriction(ctx context.Context, arg DeleteFrictionParams) error {
	_, err := q.db.Exec(ctx, deleteFriction, arg.ID, arg.UserID)
	return err
}

const getFriction = `-- name: GetFriction :one
SELECT id, user_id, task_id, work_slice_id, description, resolved_at, resolution_note, metadata, created_at, updated_at, pattern_tag FROM frictions
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetFrictionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetFriction(ctx context.Context, arg GetFrictionParams) (Friction, error) {
	row := q.db.QueryRow(ctx, getFriction, arg.ID, arg.UserID)
	var i Friction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.WorkSliceID,
		&i.Description,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PatternTag,
	)
	return i, err
}

const listFrictions = `-- name: ListFrictions :many
SELECT id, user_id, task_id, work_slice_id, description, resolved_at, resolution_note, metadata, created_at, updated_at, pattern_tag FROM frictions
WHERE user_id = $1
  AND ($4::uuid IS NULL OR task_id = $4)
  AND ($5::uuid IS NULL OR work_slice_id = $5)
  AND ($6::text IS NULL OR pattern_tag = $6)
  AND (
    $7::bool IS NULL
    OR ($7::bool = true AND resolved_at IS NOT NULL)
    OR ($7::bool = false AND resolved_at IS NULL)
  )
  AND ($8::timestamptz IS NULL OR created_at >= $8)
  AND ($9::timestamptz IS NULL OR created_at < $9)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFrictionsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
	TaskID      pgtype.UUID        `json:"task_id"`
	WorkSliceID pgtype.UUID        `json:"work_slice_id"`
	PatternTag  *string            `json:"pattern_tag"`
	Resolved    *bool              `json:"resolved"`
	FromTime    pgtype.Timestamptz `json:"from_time"`
	ToTime      pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) ListFrictions(ctx context.Context, arg ListFrictionsParams) ([]Friction, error) {
	rows, err := q.db.Query(ctx, listFrictions,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.TaskID,
		arg.WorkSliceID,
		arg.PatternTag,
		arg.Resolved,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friction{}
	for rows.Next() {
		var i Friction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.WorkSliceID,
			&i.Description,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PatternTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriction = `-- name: UpdateFriction :one
UPDATE frictions
SET task_id = $3,
    work_slice_id = $4,
    pattern_tag = $5,
    description = $6,
    resolved_at = $7,
    resolution_note = $8,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, task_id, work_slice_id, description, resolved_at, resolution_note, metadata, created_at, updated_at, pattern_tag
`

type UpdateFrictionParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	TaskID         pgtype.UUID        `json:"task_id"`
	WorkSliceID    pgtype.UUID        `json:"work_slice_id"`
	PatternTag     string             `json:"pattern_tag"`
	Description    string             `json:"description"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionNote *string            `json:"resolution_note"`
}

func (q *Queries) UpdateFriction(ctx context.Context, arg UpdateFrictionParams) (Friction, error) {
	row := q.db.QueryRow(ctx, updateFriction,
		arg.ID,
		arg.UserID,
		arg.TaskID,
		arg.WorkSliceID,
		arg.PatternTag,
		arg.Description,
		arg.ResolvedAt,
		arg.ResolutionNote,
	)
	var i Friction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.WorkSliceID,
		&i.Description,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PatternTag,
	)
	return i, err
}
