// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityEvent struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	Source     string             `json:"source"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Friction struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	TaskID         pgtype.UUID        `json:"task_id"`
	WorkSliceID    pgtype.UUID        `json:"work_slice_id"`
	Kind           string             `json:"kind"`
	Severity       int32              `json:"severity"`
	Description    string             `json:"description"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionNote *string            `json:"resolution_note"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	ExternalRef *string            `json:"external_ref"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  *string            `json:"display_name"`
	ApiKeyHash   string             `json:"api_key_hash"`
	ApiKeyPrefix string             `json:"api_key_prefix"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WorkSlice struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Mode        string             `json:"mode"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec *int32             `json:"duration_sec"`
	Note        *string            `json:"note"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
