// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTasks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountTasksByStatus(ctx context.Context, arg CountTasksByStatusParams) (int64, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetUserByAPIKeyPrefix(ctx context.Context, apiKeyPrefix string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error)
	SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (User, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
