// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountFrictions(ctx context.Context, arg CountFrictionsParams) (int64, error)
	// stall counts per (week, pattern_tag) for a category (frictions linked to that category's tasks).
	CountFrictionsByCategoryPatternWeek(ctx context.Context, arg CountFrictionsByCategoryPatternWeekParams) ([]CountFrictionsByCategoryPatternWeekRow, error)
	CountTasks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountTasksByCategory(ctx context.Context, arg CountTasksByCategoryParams) (int64, error)
	CountTasksByStatus(ctx context.Context, arg CountTasksByStatusParams) (int64, error)
	CountTasksByStatusAndCategory(ctx context.Context, arg CountTasksByStatusAndCategoryParams) (int64, error)
	CountWorkSlices(ctx context.Context, arg CountWorkSlicesParams) (int64, error)
	CreateFriction(ctx context.Context, arg CreateFrictionParams) (Friction, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkSlice(ctx context.Context, arg CreateWorkSliceParams) (WorkSlice, error)
	DeleteFriction(ctx context.Context, arg DeleteFrictionParams) error
	DeleteWorkSlice(ctx context.Context, arg DeleteWorkSliceParams) error
	GetFriction(ctx context.Context, arg GetFrictionParams) (Friction, error)
	// The single currently-open segment (state machine: at most one per user).
	GetOpenWorkSlice(ctx context.Context, userID pgtype.UUID) (WorkSlice, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetUserByAPIKeyPrefix(ctx context.Context, apiKeyPrefix string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWorkSlice(ctx context.Context, arg GetWorkSliceParams) (WorkSlice, error)
	ListActiveWorkSlices(ctx context.Context, userID pgtype.UUID) ([]WorkSlice, error)
	ListFrictions(ctx context.Context, arg ListFrictionsParams) ([]Friction, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTasksByCategory(ctx context.Context, arg ListTasksByCategoryParams) ([]Task, error)
	ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error)
	ListTasksByStatusAndCategory(ctx context.Context, arg ListTasksByStatusAndCategoryParams) ([]Task, error)
	ListWorkSlices(ctx context.Context, arg ListWorkSlicesParams) ([]WorkSlice, error)
	SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error
	// "completion time down": per week, count of completed tasks and their total own WORK time.
	// avg own-time per task = total_seconds / task_count (computed in the service).
	SumCompletedTaskTimeByCategoryWeek(ctx context.Context, arg SumCompletedTaskTimeByCategoryWeekParams) ([]SumCompletedTaskTimeByCategoryWeekRow, error)
	// Then vs Now: gross aggregations over {category × time window}, week-bucketed (ADR 005).
	// Week boundaries are cut in the client timezone (tz param), per DATA_MODEL.md.
	// mode distribution shift: total WORK seconds per (week, mode) for a category.
	SumWorkByCategoryModeWeek(ctx context.Context, arg SumWorkByCategoryModeWeekParams) ([]SumWorkByCategoryModeWeekRow, error)
	// Today distribution: total work seconds per mode for ended WORK segments in [from, to).
	SumWorkModeInRange(ctx context.Context, arg SumWorkModeInRangeParams) ([]SumWorkModeInRangeRow, error)
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (User, error)
	UpdateFriction(ctx context.Context, arg UpdateFrictionParams) (Friction, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateWorkSlice(ctx context.Context, arg UpdateWorkSliceParams) (WorkSlice, error)
}

var _ Querier = (*Queries)(nil)
