// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFrictionsByCategoryPatternWeek = `-- name: CountFrictionsByCategoryPatternWeek :many
SELECT
    date_trunc('week', f.created_at AT TIME ZONE $1::text)::timestamp AS week_start,
    f.pattern_tag AS pattern_tag,
    COUNT(*)::bigint AS cnt
FROM frictions f
JOIN tasks t ON t.id = f.task_id
WHERE f.user_id = $2
  AND t.category = $3
  AND f.created_at >= $4
  AND f.created_at < $5
GROUP BY week_start, f.pattern_tag
ORDER BY week_start, f.pattern_tag
`

type CountFrictionsByCategoryPatternWeekParams struct {
	Tz       string             `json:"tz"`
	UserID   pgtype.UUID        `json:"user_id"`
	Category string             `json:"category"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type CountFrictionsByCategoryPatternWeekRow struct {
	WeekStart  pgtype.Timestamp `json:"week_start"`
	PatternTag string           `json:"pattern_tag"`
	Cnt        int64            `json:"cnt"`
}

// stall counts per (week, pattern_tag) for a category (frictions linked to that category's tasks).
func (q *Queries) CountFrictionsByCategoryPatternWeek(ctx context.Context, arg CountFrictionsByCategoryPatternWeekParams) ([]CountFrictionsByCategoryPatternWeekRow, error) {
	rows, err := q.db.Query(ctx, countFrictionsByCategoryPatternWeek,
		arg.Tz,
		arg.UserID,
		arg.Category,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFrictionsByCategoryPatternWeekRow{}
	for rows.Next() {
		var i CountFrictionsByCategoryPatternWeekRow
		if err := rows.Scan(&i.WeekStart, &i.PatternTag, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCompletedTaskTimeByCategoryWeek = `-- name: SumCompletedTaskTimeByCategoryWeek :many
SELECT
    date_trunc('week', t.completed_at AT TIME ZONE $1::text)::timestamp AS week_start,
    COUNT(DISTINCT t.id)::bigint AS task_count,
    COALESCE(SUM(ws.duration_sec), 0)::bigint AS total_seconds
FROM tasks t
LEFT JOIN work_slices ws
    ON ws.task_id = t.id AND ws.type = 'work' AND ws.ended_at IS NOT NULL
WHERE t.user_id = $2
  AND t.category = $3
  AND t.completed_at IS NOT NULL
  AND t.completed_at >= $4
  AND t.completed_at < $5
GROUP BY week_start
ORDER BY week_start
`

type SumCompletedTaskTimeByCategoryWeekParams struct {
	Tz       string             `json:"tz"`
	UserID   pgtype.UUID        `json:"user_id"`
	Category string             `json:"category"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type SumCompletedTaskTimeByCategoryWeekRow struct {
	WeekStart    pgtype.Timestamp `json:"week_start"`
	TaskCount    int64            `json:"task_count"`
	TotalSeconds int64            `json:"total_seconds"`
}

// "completion time down": per week, count of completed tasks and their total own WORK time.
// avg own-time per task = total_seconds / task_count (computed in the service).
func (q *Queries) SumCompletedTaskTimeByCategoryWeek(ctx context.Context, arg SumCompletedTaskTimeByCategoryWeekParams) ([]SumCompletedTaskTimeByCategoryWeekRow, error) {
	rows, err := q.db.Query(ctx, sumCompletedTaskTimeByCategoryWeek,
		arg.Tz,
		arg.UserID,
		arg.Category,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumCompletedTaskTimeByCategoryWeekRow{}
	for rows.Next() {
		var i SumCompletedTaskTimeByCategoryWeekRow
		if err := rows.Scan(&i.WeekStart, &i.TaskCount, &i.TotalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumWorkByCategoryModeWeek = `-- name: SumWorkByCategoryModeWeek :many

SELECT
    date_trunc('week', ws.started_at AT TIME ZONE $1::text)::timestamp AS week_start,
    ws.mode AS mode,
    COALESCE(SUM(ws.duration_sec), 0)::bigint AS total_seconds
FROM work_slices ws
JOIN tasks t ON t.id = ws.task_id
WHERE ws.user_id = $2
  AND ws.type = 'work'
  AND ws.ended_at IS NOT NULL
  AND t.category = $3
  AND ws.started_at >= $4
  AND ws.started_at < $5
GROUP BY week_start, ws.mode
ORDER BY week_start, ws.mode
`

type SumWorkByCategoryModeWeekParams struct {
	Tz       string             `json:"tz"`
	UserID   pgtype.UUID        `json:"user_id"`
	Category string             `json:"category"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type SumWorkByCategoryModeWeekRow struct {
	WeekStart    pgtype.Timestamp `json:"week_start"`
	Mode         *string          `json:"mode"`
	TotalSeconds int64            `json:"total_seconds"`
}

// Then vs Now: gross aggregations over {category × time window}, week-bucketed (ADR 005).
// Week boundaries are cut in the client timezone (tz param), per DATA_MODEL.md.
// mode distribution shift: total WORK seconds per (week, mode) for a category.
func (q *Queries) SumWorkByCategoryModeWeek(ctx context.Context, arg SumWorkByCategoryModeWeekParams) ([]SumWorkByCategoryModeWeekRow, error) {
	rows, err := q.db.Query(ctx, sumWorkByCategoryModeWeek,
		arg.Tz,
		arg.UserID,
		arg.Category,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumWorkByCategoryModeWeekRow{}
	for rows.Next() {
		var i SumWorkByCategoryModeWeekRow
		if err := rows.Scan(&i.WeekStart, &i.Mode, &i.TotalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
