// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasks = `-- name: CountTasks :one
SELECT count(*) FROM tasks
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByCategory = `-- name: CountTasksByCategory :one
SELECT count(*) FROM tasks
WHERE user_id = $1 AND category = $2 AND deleted_at IS NULL
`

type CountTasksByCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Category string      `json:"category"`
}

func (q *Queries) CountTasksByCategory(ctx context.Context, arg CountTasksByCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByCategory, arg.UserID, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT count(*) FROM tasks
WHERE user_id = $1 AND status = $2 AND deleted_at IS NULL
`

type CountTasksByStatusParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
}

func (q *Queries) CountTasksByStatus(ctx context.Context, arg CountTasksByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByStatusAndCategory = `-- name: CountTasksByStatusAndCategory :one
SELECT count(*) FROM tasks
WHERE user_id = $1 AND status = $2 AND category = $3 AND deleted_at IS NULL
`

type CountTasksByStatusAndCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Status   string      `json:"status"`
	Category string      `json:"category"`
}

func (q *Queries) CountTasksByStatusAndCategory(ctx context.Context, arg CountTasksByStatusAndCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByStatusAndCategory, arg.UserID, arg.Status, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, user_id, title, description, category, status, external_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, description, status, external_ref, started_at, completed_at, metadata, created_at, updated_at, deleted_at, category
`

type CreateTaskParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Category    string      `json:"category"`
	Status      string      `json:"status"`
	ExternalRef *string     `json:"external_ref"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Status,
		arg.ExternalRef,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExternalRef,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Category,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, title, description, status, external_ref, started_at, completed_at, metadata, created_at, updated_at, deleted_at, category FROM tasks
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExternalRef,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Category,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, description, status, external_ref, started_at, completed_at, metadata, created_at, updated_at, deleted_at, category FROM tasks
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ExternalRef,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCategory = `-- name: ListTasksByCategory :many
SELECT id, user_id, title, description, status, external_ref, started_at, completed_at, metadata, created_at, updated_at, deleted_at, category FROM tasks
WHERE user_id = $1 AND category = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTasksByCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Category string      `json:"category"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListTasksByCategory(ctx context.Context, arg ListTasksByCategoryParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByCategory,
		arg.UserID,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ExternalRef,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, user_id, title, description, status, external_ref, started_at, completed_at, metadata, created_at, updated_at, deleted_at, category FROM tasks
WHERE user_id = $1 AND status = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTasksByStatusParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ExternalRef,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndCategory = `-- name: ListTasksByStatusAndCategory :many
SELECT id, user_id, title, description, status, external_ref, started_at, completed_at, metadata, created_at, updated_at, deleted_at, category FROM tasks
WHERE user_id = $1 AND status = $2 AND category = $3 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListTasksByStatusAndCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Status   string      `json:"status"`
	Category string      `json:"category"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListTasksByStatusAndCategory(ctx context.Context, arg ListTasksByStatusAndCategoryParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByStatusAndCategory,
		arg.UserID,
		arg.Status,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ExternalRef,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.UserID)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3,
    description = $4,
    category = $5,
    status = $6,
    external_ref = $7,
    started_at = $8,
    completed_at = $9,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, title, description, status, external_ref, started_at, completed_at, metadata, created_at, updated_at, deleted_at, category
`

type UpdateTaskParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Category    string             `json:"category"`
	Status      string             `json:"status"`
	ExternalRef *string            `json:"external_ref"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Status,
		arg.ExternalRef,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ExternalRef,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Category,
	)
	return i, err
}
