// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, api_key_hash, api_key_prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, api_key_hash, api_key_prefix, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	DisplayName  *string     `json:"display_name"`
	ApiKeyHash   string      `json:"api_key_hash"`
	ApiKeyPrefix string      `json:"api_key_prefix"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.ApiKeyHash,
		arg.ApiKeyPrefix,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAPIKeyPrefix = `-- name: GetUserByAPIKeyPrefix :one
SELECT id, email, display_name, api_key_hash, api_key_prefix, created_at, updated_at FROM users WHERE api_key_prefix = $1 LIMIT 1
`

func (q *Queries) GetUserByAPIKeyPrefix(ctx context.Context, apiKeyPrefix string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKeyPrefix, apiKeyPrefix)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, api_key_hash, api_key_prefix, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, api_key_hash, api_key_prefix, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE users
SET api_key_hash = $2, api_key_prefix = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, api_key_hash, api_key_prefix, created_at, updated_at
`

type UpdateAPIKeyParams struct {
	ID           pgtype.UUID `json:"id"`
	ApiKeyHash   string      `json:"api_key_hash"`
	ApiKeyPrefix string      `json:"api_key_prefix"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAPIKey, arg.ID, arg.ApiKeyHash, arg.ApiKeyPrefix)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.ApiKeyHash,
		&i.ApiKeyPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
