// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_slices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkSlices = `-- name: CountWorkSlices :one
SELECT count(*) FROM work_slices
WHERE user_id = $1
  AND ($2::uuid IS NULL OR task_id = $2)
  AND ($3::text IS NULL OR mode = $3)
  AND ($4::timestamptz IS NULL OR started_at >= $4)
  AND ($5::timestamptz IS NULL OR started_at < $5)
`

type CountWorkSlicesParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	TaskID   pgtype.UUID        `json:"task_id"`
	Mode     *string            `json:"mode"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) CountWorkSlices(ctx context.Context, arg CountWorkSlicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkSlices,
		arg.UserID,
		arg.TaskID,
		arg.Mode,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkSlice = `-- name: CreateWorkSlice :one
INSERT INTO work_slices (id, user_id, task_id, type, mode, driver, off_reason, started_at, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, task_id, mode, started_at, ended_at, duration_sec, note, metadata, created_at, updated_at, type, driver, off_reason
`

type CreateWorkSliceParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Type      string             `json:"type"`
	Mode      *string            `json:"mode"`
	Driver    *string            `json:"driver"`
	OffReason *string            `json:"off_reason"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Note      *string            `json:"note"`
}

func (q *Queries) CreateWorkSlice(ctx context.Context, arg CreateWorkSliceParams) (WorkSlice, error) {
	row := q.db.QueryRow(ctx, createWorkSlice,
		arg.ID,
		arg.UserID,
		arg.TaskID,
		arg.Type,
		arg.Mode,
		arg.Driver,
		arg.OffReason,
		arg.StartedAt,
		arg.Note,
	)
	var i WorkSlice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Mode,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.Note,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Driver,
		&i.OffReason,
	)
	return i, err
}

const deleteWorkSlice = `-- name: DeleteWorkSlice :exec
DELETE FROM work_slices WHERE id = $1 AND user_id = $2
`

type DeleteWorkSliceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkSlice(ctx context.Context, arg DeleteWorkSliceParams) error {
	_, err := q.db.Exec(ctx, deleteWorkSlice, arg.ID, arg.UserID)
	return err
}

const getOpenWorkSlice = `-- name: GetOpenWorkSlice :one
SELECT id, user_id, task_id, mode, started_at, ended_at, duration_sec, note, metadata, created_at, updated_at, type, driver, off_reason FROM work_slices
WHERE user_id = $1 AND ended_at IS NULL
ORDER BY started_at DESC
LIMIT 1
`

// The single currently-open segment (state machine: at most one per user).
func (q *Queries) GetOpenWorkSlice(ctx context.Context, userID pgtype.UUID) (WorkSlice, error) {
	row := q.db.QueryRow(ctx, getOpenWorkSlice, userID)
	var i WorkSlice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Mode,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.Note,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Driver,
		&i.OffReason,
	)
	return i, err
}

const getWorkSlice = `-- name: GetWorkSlice :one
SELECT id, user_id, task_id, mode, started_at, ended_at, duration_sec, note, metadata, created_at, updated_at, type, driver, off_reason FROM work_slices
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetWorkSliceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkSlice(ctx context.Context, arg GetWorkSliceParams) (WorkSlice, error) {
	row := q.db.QueryRow(ctx, getWorkSlice, arg.ID, arg.UserID)
	var i WorkSlice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Mode,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.Note,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Driver,
		&i.OffReason,
	)
	return i, err
}

const listActiveWorkSlices = `-- name: ListActiveWorkSlices :many
SELECT id, user_id, task_id, mode, started_at, ended_at, duration_sec, note, metadata, created_at, updated_at, type, driver, off_reason FROM work_slices
WHERE user_id = $1 AND ended_at IS NULL
ORDER BY started_at DESC
`

func (q *Queries) ListActiveWorkSlices(ctx context.Context, userID pgtype.UUID) ([]WorkSlice, error) {
	rows, err := q.db.Query(ctx, listActiveWorkSlices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkSlice{}
	for rows.Next() {
		var i WorkSlice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Mode,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.Note,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.Driver,
			&i.OffReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkSlices = `-- name: ListWorkSlices :many
SELECT id, user_id, task_id, mode, started_at, ended_at, duration_sec, note, metadata, created_at, updated_at, type, driver, off_reason FROM work_slices
WHERE user_id = $1
  AND ($4::uuid IS NULL OR task_id = $4)
  AND ($5::text IS NULL OR mode = $5)
  AND ($6::timestamptz IS NULL OR started_at >= $6)
  AND ($7::timestamptz IS NULL OR started_at < $7)
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkSlicesParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	Limit    int32              `json:"limit"`
	Offset   int32              `json:"offset"`
	TaskID   pgtype.UUID        `json:"task_id"`
	Mode     *string            `json:"mode"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) ListWorkSlices(ctx context.Context, arg ListWorkSlicesParams) ([]WorkSlice, error) {
	rows, err := q.db.Query(ctx, listWorkSlices,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.TaskID,
		arg.Mode,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkSlice{}
	for rows.Next() {
		var i WorkSlice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Mode,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSec,
			&i.Note,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.Driver,
			&i.OffReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumWorkModeInRange = `-- name: SumWorkModeInRange :many
SELECT mode, COALESCE(SUM(duration_sec), 0)::bigint AS total_seconds
FROM work_slices
WHERE user_id = $1
  AND type = 'work'
  AND ended_at IS NOT NULL
  AND started_at >= $2
  AND started_at < $3
GROUP BY mode
`

type SumWorkModeInRangeParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type SumWorkModeInRangeRow struct {
	Mode         *string `json:"mode"`
	TotalSeconds int64   `json:"total_seconds"`
}

// Today distribution: total work seconds per mode for ended WORK segments in [from, to).
func (q *Queries) SumWorkModeInRange(ctx context.Context, arg SumWorkModeInRangeParams) ([]SumWorkModeInRangeRow, error) {
	rows, err := q.db.Query(ctx, sumWorkModeInRange, arg.UserID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumWorkModeInRangeRow{}
	for rows.Next() {
		var i SumWorkModeInRangeRow
		if err := rows.Scan(&i.Mode, &i.TotalSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkSlice = `-- name: UpdateWorkSlice :one
UPDATE work_slices
SET task_id = $3,
    mode = $4,
    driver = $5,
    off_reason = $6,
    started_at = $7,
    ended_at = $8,
    duration_sec = $9,
    note = $10,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, task_id, mode, started_at, ended_at, duration_sec, note, metadata, created_at, updated_at, type, driver, off_reason
`

type UpdateWorkSliceParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Mode        *string            `json:"mode"`
	Driver      *string            `json:"driver"`
	OffReason   *string            `json:"off_reason"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec *int32             `json:"duration_sec"`
	Note        *string            `json:"note"`
}

func (q *Queries) UpdateWorkSlice(ctx context.Context, arg UpdateWorkSliceParams) (WorkSlice, error) {
	row := q.db.QueryRow(ctx, updateWorkSlice,
		arg.ID,
		arg.UserID,
		arg.TaskID,
		arg.Mode,
		arg.Driver,
		arg.OffReason,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSec,
		arg.Note,
	)
	var i WorkSlice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Mode,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
		&i.Note,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Driver,
		&i.OffReason,
	)
	return i, err
}
